---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres-ingress
  annotations:
    external-dns.alpha.kubernetes.io/target: "192.168.50.160,192.168.50.182,192.168.50.234"
spec:
  ingressClassName: internal
  rules:
  - host: postgres.${SECRET_DOMAIN}  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-postgres16-rw
            port: 
              number: 5432