---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: miniflux-secret
    template:
      engineVersion: v2
      data:
        # App
        ADMIN_USERNAME: "{{ .MINIFLUX_ADMIN_USERNAME }}"
        ADMIN_PASSWORD: "{{ .MINIFLUX_ADMIN_PASSWORD }}"
        DATABASE_URL: "postgres://{{ .MINIFLUX_POSTGRES_USER }}:{{ .MINIFLUX_POSTGRES_PASS }}@dev-postgres16-rw.database.svc.cluster.local:5432/miniflux?sslmode=disable"
        # Postgres Init
        INIT_POSTGRES_DBNAME: miniflux
        INIT_POSTGRES_HOST: "dev-postgres16-rw.database.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .MINIFLUX_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .MINIFLUX_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: cloudnative-pg
        property: password

    - secretKey: MINIFLUX_ADMIN_USERNAME
      remoteRef:
        key: miniflux
        property: username
    - secretKey: MINIFLUX_ADMIN_PASSWORD
      remoteRef:
        key: miniflux
        property: password

    - secretKey: MINIFLUX_POSTGRES_USER
      remoteRef:
        key: miniflux-db
        property: username
    - secretKey: MINIFLUX_POSTGRES_PASS
      remoteRef:
        key: miniflux-db
        property: password

