---
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: qbittorrent-egress
spec:
  # 选择qbittorrent pod
  selectors:
  - podSelector:
      matchLabels:
        app.kubernetes.io/name: qbittorrent

  # 指定所有外部目标（BitTorrent流量）
  destinationCIDRs:
  - "0.0.0.0/0"

  # 排除集群内部网络，确保只有真正的外部流量使用EgressGateway
  excludedCIDRs:
  - "10.0.0.0/8"        # Kubernetes集群网络
  - "172.16.0.0/12"     # Docker网络
  - "192.168.50.220/32" # NFS服务器
  - "192.168.50.145/32" # 节点IP
  - "192.168.50.10/32"  # 避免自循环

  # 配置网关节点 - 使用独立的IP地址
  egressGateway:
    nodeSelector:
      matchLabels:
        kubernetes.io/os: linux
    # 指定专用的出站IP - qbittorrent专用！
    egressIP: 192.168.50.10
