---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  # - ./network-policy.yaml
  - ./egress-gateway-policy.yaml
  # - ../../../../templates/gatus/external
  # - ../../../../templates/volsync
  # - ../../../../templates/volsync-restore
