---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paper-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: topolvm-thin-provisioner

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paper
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: topolvm-thin-provisioner
