---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yt-audio
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: topolvm-thin-provisioner
