---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: prowlarr-secret
    template:
      engineVersion: v2
      data:
        PROWLARR__AUTH__APIKEY: "{{ .PROWLARR_API_KEY }}"
        PROWLARR__POSTGRES__HOST: &dbHost "dev-postgres16-rw.database.svc.cluster.local"
        PROWLARR__POSTGRES__PORT: "5432"
        PROWLARR__POSTGRES__USER: &dbUser "{{ .PROWLARR__POSTGRES_USER }}"
        PROWLARR__POSTGRES__PASSWORD: &dbPass "{{ .PROWLARR__POSTGRES_PASSWORD }}"
        PROWLARR__POSTGRES__MAINDB: "prowlarr_main"
        # Postgres Init
        INIT_POSTGRES_DBNAME: prowlarr_main prowlarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  data:
  - secretKey: POSTGRES_SUPER_PASS
    remoteRef:
      key: cloudnative-pg
      property: password
  - secretKey: PROWLARR__POSTGRES_USER
    remoteRef:
      key: prowlarr-db
      property: username
  - secretKey: PROWLARR__POSTGRES_PASSWORD
    remoteRef:
      key: prowlarr-db
      property: password
  - secretKey: PROWLARR_API_KEY
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 30e19462-7e38-4e3e-8bf8-94c459c5f5e7
      property: PROWLARR_API_KEY

