---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: alertmanager-secret
    template:
      data:
        ALERTMANAGER_PUSHOVER_TOKEN: "{{ .ALERTMANAGER_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  data:
    - secretKey: ALERTMANAGER_PUSHOVER_TOKEN
      remoteRef:
        key: pushover_alert_dev
        property: password
    - secretKey: PUSHOVER_USER_KEY
      remoteRef:
        key: pushover_alert_dev
        property: username