---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/imagepolicy-image-reflector-v1.json
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: fava
  namespace: default
spec:
  imageRepositoryRef:
    name: fava
  policy:
    alphabetical:
      order: asc
