apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
spec:
  interval: 1h
  chart:
    spec:
      chart: local-path-provisioner
      version: 0.0.32
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
        namespace: flux-system
      interval: 1h
  releaseName: local-path-provisioner
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    defaultVolumeType: local
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        path: "/var/local-path-provisioner"

