---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: openclaw-secret
    template:
      engineVersion: v2
      data:
        OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
        BRAVE_API_KEY: "{{ .BRAVE_API_KEY }}"
        FIRECRAWL_API_KEY: "{{ .FIRECRAWL_API_KEY }}"
        GEMINI_API_KEY: "{{ .GEMINI_API_KEY }}"
        TAVILY_API_KEY: "{{ .TAVILY_API_KEY }}"
  data:
    - secretKey: OPENCLAW_GATEWAY_TOKEN
      remoteRef:
        key: ff23aca9-8b0c-4015-be14-a64b01ab2b49
        property: OPENCLAW_GATEWAY_TOKEN
    - secretKey: BRAVE_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: BRAVE_API_KEY
        property: password
    - secretKey: FIRECRAWL_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: FIRECRAWL_API_KEY
        property: password
    - secretKey: GEMINI_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: GEMINI_API_KEY
        property: password
    - secretKey: TAVILY_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: TAVILY_API_KEY
        property: password
