---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: n8n-secret
    template:
      engineVersion: v2
      data:
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
        DB_TYPE: postgresdb
        DB_POSTGRESDB_DATABASE: &dbName n8n
        DB_POSTGRESDB_HOST: &dbHost "dev-postgres16-rw.database.svc.cluster.local"
        DB_POSTGRESDB_USER: &dbUser "{{ .N8N__POSTGRES_USER }}"
        DB_POSTGRESDB_PASSWORD: &dbPass "{{ .N8N__POSTGRES_PASSWORD }}"
        DB_POSTGRESDB_PORT: "5432"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: cloudnative-pg
        property: password
    - secretKey: N8N__POSTGRES_USER
      remoteRef:
        key: n8n-db
        property: username
    - secretKey: N8N__POSTGRES_PASSWORD
      remoteRef:
        key: n8n-db
        property: password
    - secretKey: N8N_ENCRYPTION_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 4b8ea3c5-a031-4576-a6e0-bd86b7399d84
        property: N8N_ENCRYPTION_KEY