---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-relay-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: smtp-relay-secret
    template:
      engineVersion: v2
      data:
        SMTP_RELAY_SERVER: "{{ .SMTP_RELAY_SERVER }}"
        SMTP_RELAY_USERNAME: "{{ .SMTP_RELAY_USERNAME }}"
        SMTP_RELAY_PASSWORD: "{{ .SMTP_RELAY_PASSWORD }}"
  data:
    - secretKey: SMTP_RELAY_SERVER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: e7305b42-14a8-4ed6-8594-0059051c4742
        property: HOST
    - secretKey: SMTP_RELAY_USERNAME
      remoteRef:
        key: smtp-relay
        property: username
    - secretKey: SMTP_RELAY_PASSWORD
      remoteRef:
        key: smtp-relay
        property: password