---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: gitea-runner-secret
    template:
      engineVersion: v2
      data:
        GITEA_RUNNER_REGISTRATION_TOKEN: "{{ .GITEA_RUNNER_REGISTRATION_TOKEN }}"

  data:
    - secretKey: GITEA_RUNNER_REGISTRATION_TOKEN
      remoteRef:
        key: gitea-runner
        property: password

