---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
spec:
  accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "volsync-dst-${APP}"
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY:-1Gi}"
  storageClassName: "${VOLSYNC_STORAGECLASS:-local-path}"
