---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    template:
      data:
        admin-user: "{{ .username}}"
        admin-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: grafana
        property: password
    - secretKey: username
      remoteRef:
        key: grafana
        property: username
