endpoints:
  - name: "${APP}"
    group: external
    url: "https://${GATUS_SUBDOMAIN:=${APP}}.${SECRET_DOMAIN}${GATUS_PATH:=/}"
    interval: 1m
    client:
      dns-resolver: tcp://223.5.5.5:53
    conditions:
      - "[STATUS] == ${GATUS_STATUS:=200}"
