# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:5tMkbhhYjzHneZfPiqjdu1H7+/zy17yL24EraEaczJrWxzQteRoh+SUPxmpYjgtYMbXokAl6oQXHoRvcPRKYwtBLHtCZJrWo3vvh6vwwlzhr+57JyGSgyv5ICuXsO7Jd+AMLonRtfDK/ZquXdzk07cv3Ha7NsfSR1Ybp/gaCxrEUmiq/yU0+UpSwEj0iLTBXKahTLPIgrNB3hSoFvxoJRL2WaYjOKkMwhaNoYpfKQYp9WWfh,iv:K3uCOI/WSvzBYLZy6SP3EenNEfiVEnyCpvHRXcTEOTE=,tag:WNpwYcEcQk5jFlyXLIolgg==,type:str]
sops:
  age:
    - recipient: age1shkd7fsr66cnpkutpmpf7ffylcc2x4c9tlsdkapv6nmu5ceu0dzqdjtqc5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MFNzQkpHV0VJVlo0U1JF
        ZkwrRWJrOVZIVE4vNzlIWlM5anpMeUtPOVQwCncyM0ZtVHYzZWdQaXdMaTlQcFlm
        YnY0YTZNZXN0ZnE5UmE0bUYrbHhpb2cKLS0tIC9jMFE1YmFKZHRtSm9JelFSNGsr
        ZlU3ZkM0NHBCWk1pd3hCZXZCT3BkZ1EKY63h980EGSDLFKEs4m1OBCmfax0b9RU5
        CBB6ij/WqG61rpoDDahYogXXnhI4Dh++r9eCc/oWQ0qAYBWlLWDF8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-14T13:25:41Z"
  mac: ENC[AES256_GCM,data:zfSRvvdROHQ6HUwEHfNg0JoqrXXBsYFW/Z+vjO2LPx58tF9VNR5cxvClsETeHTXNLK7DaWeCOW/lNib/HGd+/5fdPZow0Ox7vEF5wgO0sj/rdB1IocDURK26kCKvfvvkUNnp+cp60Kc6DNlThimkKm8bjyy0ET98F8rx27Kg2Yk=,iv:EcsXJ1LDOf7UInpqwKRiHdZZZK7R8by8KkThXIYP6Y8=,tag:pzYMFAe5aMewLHSqd4yTgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
