apiVersion: v1
data:
    BW_HOST: ENC[AES256_GCM,data:9BWMUT6jnV3riSTXRcuGVAHqq9J4QEioqtudZsWiBF8=,iv:TMoHbXEECK8as2W+m/q8uVop+iVtY1+fdTBIqLBrXBA=,tag:hH+qKeSUn0FTNAQKcJKxqA==,type:str]
    BW_USERNAME: ENC[AES256_GCM,data:m1TEpvXIzVY8TV+i10yP9TElh5M=,iv:64FC1+l3rHf49AGU6qN/3XQk9DDa0cTSgnGhS7tRvE0=,tag:LXnfRGheIjO4xumbC3Bhhg==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:ewBoopIhlC9lmDQU6oTm6A==,iv:ght9eC/M7WSfxUw9MIYQmJu+j/w6cOsiu+aW9pw/e+E=,tag:Xsa9zxaRJOQXFOI3KUY6ew==,type:str]
    #ENC[AES256_GCM,data:UgiPmD3Mz1dfqS/ooEueJlKqa4bsLs6hfg4JkkEJR9xK4vV5J5uBwzpH04R8Q0mI,iv:R0bd/Wm8ylwQqMTf3YCgUaVn4vwUq/gf15eFlOlrowg=,tag:ejkcOa8dcx2XFFMW2p7YCA==,type:comment]
    BW_CLIENTID: ENC[AES256_GCM,data:Smd4JKGVT16eUbF0IHpoD1Q/nRRsRBQbPFbqRCg6Cli9V7Hl2VjLIC+ngW4RLkurW9T8V6LhDLE=,iv:42IwKUhziIknZgBw4viI6lb0e9H/G+EoaVNx5/QfQAg=,tag:AmpcHbNXiFpOhwwyfZ8/ew==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:2L31Ep3IKLfcfXXaH/etxIpFP8OKpD38c6/h1bBwJUM+BNOZ2h5dCg==,iv:nmSp9KAh04pMmg7vAUhqfhS12jHEPD2jIXQSiomaezU=,tag:5YhPGUXkPcN+9dBYHjDR/w==,type:str]
kind: Secret
metadata:
    name: bitwarden-cli
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17hs3k9rfp2n3xn38nl8kks4sppj4n98dxfxdhe2x73d86sh0t54slpn33d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOGVZRGtUQkd4V3kvYzlt
            UjI2Z0VLeHBWL1RZNDM4OGJxZmtGY2liSkdZCnlxclE4Y2c1YUpLWHI3aTI1eHhR
            UE1jSFluR1VyTCtTQi94NS9zaUtlQ2cKLS0tIGsycjhEbXI1Wk5YTWVXQ0Y0OURC
            L2xxRFFmMWoyQVFMTUtUdzY5MDkvL2sKWy9CogPC4FloJvFuB3E4csIgKrJ1yhAy
            2lzObTzbh7CEZgGn8wacvP1XKAS6mTVmSiskdBajvBnOjNbcHL/slg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T11:53:43Z"
    mac: ENC[AES256_GCM,data:VO3V5MElYzjN8eTt97wF65NEIjX2S77pB3Z31HxfN1YSnPaWS26Ub7Hf46DoOgZk/+RkdStrmvARzMS+X+DBpWL/r5I3x1vjuUKPm6TUUTw8zce63mLeO/8BhV0JnddM3/GwsdWYg17xWv6D1zXYrY1gAVtCvlDf9otAlu6Odk4=,iv:0ea+FScqZMKWTKoXW9HSI9tPD5Ix/zSyecBSQX9KeD4=,tag:qCcCM/mhJq549+uqDLAMwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
