---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omnifocus-sync-server
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: omnifocus-sync-server-secret
    template:
      engineVersion: v2
      data:
        API_KEY: "{{ .API_KEY }}"
  data:
    - secretKey: API_KEY
      remoteRef:
        key: OMNIFOCUS_SYNC_API_KEY
        property: password
