---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omnifocus-sync-server-registry
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: omnifocus-sync-server-registry-secret
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{"auths":{"gitea.tomyail.com":{"username":"{{ .REGISTRY_USERNAME }}","password":"{{ .REGISTRY_PASSWORD }}","auth":"{{ printf "%s:%s" .REGISTRY_USERNAME .REGISTRY_PASSWORD | b64enc }}"}}}'
  data:
    - secretKey: REGISTRY_USERNAME
      remoteRef:
        key: d01d04c2-30c2-4afe-b19b-10dfaced8670
        property: username
    - secretKey: REGISTRY_PASSWORD
      remoteRef:
        key: d01d04c2-30c2-4afe-b19b-10dfaced8670
        property: password
