apiVersion: v1
kind: Service
metadata:
  name: cold-minio-api
spec:
  ports:
    - port: 9010
      targetPort: 9010
---
apiVersion: v1
kind: Service
metadata:
  name: hot-minio-api
spec:
  ports:
    - port: 9000
      targetPort: 9000
