---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/imageupdateautomation-image-automation-v1.json
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: fava
spec:
  interval: 5m
  update:
    strategy: Setters
    path: ./kubernetes/apps/default/fava
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux-bot
        email: flux-bot@users.noreply.github.com
      messageTemplate: |
        Automated image update

        Files:
        {{ range .Changed.Files }}
        - {{ .Path }}
        {{ end }}

        Images:
        {{ range .Changed.Images }}
        - {{ .Repository }}:{{ .Tag }}
        {{ end }}

        Built by Flux Image Automation
    push:
      branch: main

