---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: adguard-dns
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.17.0
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app adguard-dns
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: adguard-dns
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v9.0.1@sha256:08fc9f649dbab69bc3474b102b0098262ffbd2281509443d10a697dadb1eaa77
        env:
          - name: LOG_LEVEL
            value: debug
          - name: ADGUARD_URL
            value: http://192.168.50.137:8080
          - name: ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: &secret adguard-dns-secret
                key: ADGUARD_USER
          - name: ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: *secret
                key: ADGUARD_PASSWORD
          - name: DRY_RUN
            value: 'false'
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
    triggerLoopOnEvent: true
    policy: sync
    sources: ['gateway-httproute', 'gateway-tlsroute']
    txtOwnerId: default
    txtPrefix: k8s.
    serviceMonitor:
      enabled: true
      endpoints:
        - path: /metrics
          port: http
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    terminationGracePeriodSeconds: 120
    extraArgs:
      - --gateway-name=internal
