---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lidarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: lidarr-secret
    template:
      engineVersion: v2
      data:
        LIDARR__AUTH__APIKEY: "{{ .LIDARR_API_KEY }}"
        PROWLARR__POSTGRES__HOST: &dbHost "dev-postgres16-rw.database.svc.cluster.local"
        PROWLARR__POSTGRES__PORT: "5432"
        LIDARR__POSTGRES__USER: &dbUser "{{ .LIDARR__POSTGRES_USER }}"
        LIDARR__POSTGRES__PASSWORD: &dbPass "{{ .LIDARR__POSTGRES_PASSWORD }}"
        LIDARR__POSTGRES__MAINDB: "lidarr_main"
        # Postgres Init
        INIT_POSTGRES_DBNAME: lidarr_main
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  data:
  - secretKey: POSTGRES_SUPER_PASS
    remoteRef:
      key: cloudnative-pg
      property: password
  - secretKey: LIDARR__POSTGRES_USER
    remoteRef:
      key: lidarr-db
      property: username
  - secretKey: LIDARR__POSTGRES_PASSWORD
    remoteRef:
      key: lidarr-db
      property: password
  - secretKey: LIDARR_API_KEY
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 8362a1be-a12c-441e-99aa-5e11558d25eb
      property: LIDARR_API_KEY

