---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app growth-tracker
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/image-automation
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
    - name: cloudnative-pg-cluster
      namespace: database
  path: ./kubernetes/apps/default/growth-tracker/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true
  wait: true
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      NAMESPACE: *namespace
      REGISTRY_URL: gitea.tomyail.com/tomyail/growth-tracker
      REGISTRY_HOST: gitea.tomyail.com
      BW_ID: d01d04c2-30c2-4afe-b19b-10dfaced8670
