---
web:
  port: ${WEB_PORT}
storage:
  type: sqlite
  path: /config/sqlite.db
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: 电信光猫
    group: local
    url: icmp://192.168.71.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: 移动光猫
    group: local
    url: icmp://192.168.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: flux-webhook
    group: external
    url: https://flux-webhook.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"