# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:N8kLJtjPSkHjfEGZDdJrFqL7eJLwNxNor/3pkrXUgSXLccMeZOUnwg==,iv:8v4ZBU9znhFgOeE0RECiCSbkw3LHc1PN+TlhDba7Zeo=,tag:0We8bKuD4O4NxgzSji/neQ==,type:str]
sops:
  age:
    - recipient: age1shkd7fsr66cnpkutpmpf7ffylcc2x4c9tlsdkapv6nmu5ceu0dzqdjtqc5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1K01jeXBnT0g5SWNWeXl1
        Nm9zYUVadGl3T3BMVllpT3hwV2laeC9naFF3ClUyamI1WkFRalY0ZG95QlNmNVJa
        NktpKzVOMWpLcE9OZ1FZSE9rV1d4eEkKLS0tIGhLTlZRK2hQVjNiQ3gwVjVyMS90
        azJnaXlyZHduQlRWQWQxMy8vRll3elEKe++GN1zw09+SlE9EB6hinnnuU7QQ38l9
        02Dp29p4N01cehqWZ8iicHwon6B0Fhvs9eGsUQ3uXJ3K9YV2PwdWCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-14T13:25:41Z"
  mac: ENC[AES256_GCM,data:3zRKKll58Dt12t8pAVmGDgZG8DjZxY56d9RTcptH7ZEFTdyijQn23wUdRCXQZx8fxlBc1CV1jykLwHLz5wWIMYPQ1dr1HIKbR+L2kBK50SRZAZbhi4qz22kVT2tNhVRPWsvcYeWpHMnTEl1ppFLyZZ9ktjrkJponZYkAczzWJdE=,iv:JAN/cREF1arSnLOIuHmfA4YPp5xRcfAFOlQ0egxON3Q=,tag:Q9NdbypdspnrlDcQOrBXeQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
