---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: radarr-secret
    template:
      engineVersion: v2
      data:
        RADARR__AUTH__APIKEY: "{{ .RADARR_API_KEY }}"
        RADARR__POSTGRES__HOST: &dbHost "dev-postgres16-rw.database.svc.cluster.local"
        RADARR__POSTGRES__PORT: "5432"
        RADARR__POSTGRES__USER: &dbUser "{{ .RADARR__POSTGRES_USER }}"
        RADARR__POSTGRES__PASSWORD: &dbPass "{{ .RADARR__POSTGRES_PASSWORD }}"
        RADARR__POSTGRES__MAINDB: "radarr_main"
        RADARR__POSTGRES__LOGDB: "radarr_log"
        # Postgres Init
        INIT_POSTGRES_DBNAME: radarr_main radarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  data:
  - secretKey: POSTGRES_SUPER_PASS
    remoteRef:
      key: cloudnative-pg
      property: password
  - secretKey: RADARR__POSTGRES_USER
    remoteRef:
      key: radarr-db
      property: username
  - secretKey: RADARR__POSTGRES_PASSWORD
    remoteRef:
      key: radarr-db
      property: password
  - secretKey: RADARR_API_KEY
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 14fe56b2-1e05-435e-a181-059419a24825
      property: RADARR_API_KEY

