---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: jellyseerr-secret
    template:
      engineVersion: v2
      data:
        DB_TYPE: "postgres"
        DB_HOST: &dbHost "dev-postgres16-rw.database.svc.cluster.local"
        DB_PORT: "5432"
        DB_USER: &dbUser "{{ .JELLYSEERR__POSTGRES_USER }}"
        DB_PASS: &dbPass "{{ .JELLYSEERR__POSTGRES_PASSWORD }}"
        DB_NAME: "jellyseerr"
        API_KEY: "{{ .JELLYSEERR_API_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: jellyseerr
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  data:
  - secretKey: POSTGRES_SUPER_PASS
    remoteRef:
      key: cloudnative-pg
      property: password
  - secretKey: JELLYSEERR__POSTGRES_USER
    remoteRef:
      key: jellyseerr-db
      property: username
  - secretKey: JELLYSEERR__POSTGRES_PASSWORD
    remoteRef:
      key: jellyseerr-db
      property: password
  - secretKey: JELLYSEERR_API_KEY
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 9340af49-3add-4274-b2a0-7e6d16c84416
      property: JELLYSEERR_API_KEY

