---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: paperless-secret
    template:
      engineVersion: v2
      data:
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
  data:
  - secretKey: PAPERLESS_ADMIN_USER
    remoteRef:
      key: paperless
      property: username
  - secretKey: PAPERLESS_ADMIN_PASSWORD
    remoteRef:
      key: paperless
      property: password
  - secretKey: PAPERLESS_SECRET_KEY
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 6a773e6f-82a5-422e-bea1-713ef78bfb41
      property: PAPERLESS_SECRET_KEY
