apiVersion: batch/v1
kind: CronJob
metadata:
  name: minio-to-nfs-sync
spec:
  schedule: "0 3 * * *" # Run daily at 3:00 AM, adjust as needed
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rclone-sync
            image: rclone/rclone:latest
            command: ["/bin/sh", "-c"]
            args:
              - |
                set -e # Exit immediately if a command exits with a non-zero status.
                echo "Starting MinIO to NFS sync..."
                rclone sync -v "miniosrc:db-backups" "/nfs-backup/db-backups" && \
                echo "Syncing obsidian..." && \
                rclone sync -v "miniosrc:obsidian" "/nfs-backup/obsidian" && \
                echo "Syncing restic-backup..." && \
                rclone sync -v "miniosrc:restic-backup" "/nfs-backup/restic-backup" && \
                echo "Syncing user..." && \
                rclone sync -v "miniosrc:user" "/nfs-backup/user"
                echo "MinIO to NFS sync finished successfully."
            envFrom:
            - secretRef:
                name: minio-sync-secret
            volumeMounts:
            - name: nfs-backup
              mountPath: /nfs-backup
          volumes:
          - name: nfs-backup
            nfs:
              server: 192.168.50.220
              path: /volume4/AppDataHDD/prod-minio-backup
          restartPolicy: OnFailure
