endpoints:
  - name: "${APP}"
    group: tailscale
    url: "https://${GATUS_SUBDOMAIN_TAILSCALE:=${APP}}.${SECRET_DOMAIN}${GATUS_PATH:=/}"
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == ${GATUS_STATUS:=200}"