---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: recyclarr-secret
    template:
      engineVersion: v2
      data:
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
  data:
    - secretKey: RADARR_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 14fe56b2-1e05-435e-a181-059419a24825
        property: RADARR_API_KEY
    - secretKey: SONARR_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: e24f2ae2-9ae9-4c52-934b-026c8333c293
        property: SONARR_API_KEY