---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: ${APP}
  namespace: ${NAMESPACE}
  labels:
    image-automation: enabled
spec:
  imageRepositoryRef:
    name: ${APP}
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: "^.+-[a-f0-9]+-(?P<ts>[0-9]+)$"
    extract: "$ts"
