---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ${APP}
  namespace: ${NAMESPACE}
  labels:
    image-automation: enabled
spec:
  imageRepositoryRef:
    name: ${APP}
  policy:
    alphabetical:
      order: desc
  filterTags:
    pattern: "^sha-[a-f0-9]+$"
