---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ${APP}
  namespace: ${NAMESPACE}
spec:
  image: ${REGISTRY_URL}
  interval: 1m
  secretRef:
    name: ${APP}-registry-secret
