---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: atuin-secret
    template:
      engineVersion: v2
      data:
        ATUIN_DB_URI: |-
          postgres://{{ .ATUIN_POSTGRES_USER }}:{{ .ATUIN_POSTGRES_PASS }}@dev-postgres16-rw.database.svc.cluster.local/atuin
        INIT_POSTGRES_DBNAME: atuin
        INIT_POSTGRES_HOST: dev-postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .ATUIN_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .ATUIN_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: cloudnative-pg
        property: password
    - secretKey: ATUIN_POSTGRES_USER
      remoteRef:
        key: atuin-db
        property: username
    - secretKey: ATUIN_POSTGRES_PASS
      remoteRef:
        key: atuin-db
        property: password


