---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rsshub
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: rsshub-secret
    template:
      engineVersion: v2
      data:
        TWITTER_USERNAME: '{{ .TWITTER_USERNAME }}'
        TWITTER_PASSWORD: '{{ .TWITTER_PASSWORD }}'
        TWITTER_AUTH_TOKEN: '{{ .TWITTER_AUTH_TOKEN }}'
        CAIXIN_COOKIE: '{{ .CAIXIN_COOKIE }}'

  data:
  - secretKey: TWITTER_USERNAME
    remoteRef:
      key: twitter
      property: username
  - secretKey: TWITTER_PASSWORD
    remoteRef:
      key: twitter
      property: password
  - secretKey: TWITTER_AUTH_TOKEN
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 145ad809-c1aa-4dd7-a335-8ddd4fc5c3fd
      property: auth_token
  - secretKey: CAIXIN_COOKIE
    remoteRef:
      key: caixin-cookie
      property: password