---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rsshub
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: rsshub-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  data:
  - secretKey: POSTGRES_SUPER_PASS
    remoteRef:
      key: cloudnative-pg
      property: password