---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rsshub
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: rsshub-secret
    template:
      engineVersion: v2
      data:
        TWITTER_USERNAME: '{{ .TWITTER_USERNAME }}'
        TWITTER_PASSWORD: '{{ .TWITTER_PASSWORD }}'

  data:
  - secretKey: TWITTER_USERNAME
    remoteRef:
      key: twitter
      property: username
  - secretKey: TWITTER_PASSWORD
    remoteRef:
      key: twitter
      property: password
