---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.86.5
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  values:
      # TODO: currently not supported by the operator
    fullnameOverride: *app
    operatorConfig:
      hostname: tailscale
      podAnnotations:
        reloader.stakater.com/auto: "true"
    apiServerProxyConfig:
      mode: 'true'
  valuesFrom:
    - kind: Secret
      name: tailscale-secret
      valuesKey: client_id
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-secret
      valuesKey: client_secret
      targetPath: oauth.clientSecret

