---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        foo: bar
        # HASS_DARKSKY_API_KEY: "{{ .HASS_DARKSKY_API_KEY }}"
        # HASS_ECOBEE_API_KEY: "{{ .HASS_ECOBEE_API_KEY }}"
        # HASS_ELEVATION: "{{ .HASS_ELEVATION }}"
        # HASS_GOOGLE_PROJECT_ID: "{{ .HASS_GOOGLE_PROJECT_ID }}"
        # HASS_GOOGLE_SECURE_DEVICES_PIN: "{{ .HASS_GOOGLE_SECURE_DEVICES_PIN }}"
        # HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        # HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        # HASS_PIRATE_WEATHER_API_KEY: "{{ .HASS_PIRATE_WEATHER_API_KEY }}"
  data:
  - secretKey: password
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 2ec3c1dd-c4d3-45f7-bbeb-12c2e4fcb67e
      property: webhook_token
