---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        HASS_POSTGRES_HOST: &dbHost dev-postgres16-rw.database.svc.cluster.local
        HASS_POSTGRES_USER: &dbUser "{{ .HASS__POSTGRES_USER }}"
        HASS_POSTGRES_PASSWORD: &dbPass "{{ .HASS__POSTGRES_PASSWORD }}"
        HASS_POSTGRES_URL: "postgresql://{{ .HASS__POSTGRES_USER }}:{{ .HASS__POSTGRES_PASSWORD }}@dev-postgres16-rw.database.svc.cluster.local/home_assistant"
        # Postgres Init
        INIT_POSTGRES_DBNAME: home_assistant
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: cloudnative-pg
        property: password
    - secretKey: HASS__POSTGRES_USER
      remoteRef:
        key: hass-db
        property: username
    - secretKey: HASS__POSTGRES_PASSWORD
      remoteRef:
        key: hass-db
        property: password
