---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: epub-translator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: epub-translator-secret
    template:
      engineVersion: v2
      data:
        PUSHOVER_TOKEN: "{{ .PUSHOVER_TOKEN }}"
        PUSHOVER_USER: "{{ .PUSHOVER_USER }}"
        NEXTCLOUD_USERNAME: "{{ .NEXTCLOUD_USERNAME }}"
        NEXTCLOUD_PASSWORD: "{{ .NEXTCLOUD_PASSWORD }}"
        format.json: |
          {
            "key": "{{ .LITELLM_AUTH_TOKEN }}",
            "url": "http://litellm.default.svc.cluster.local:4000/v1",
            "model": "deepseek-v4-flash",
            "token_encoding": "cl100k_base",
            "timeout": 360.0,
            "retry_times": 10,
            "retry_interval_seconds": 0.75,
            "translation": {"temperature": 0.8, "top_p": 0.6},
            "fill": {"temperature": [0.2, 0.9], "top_p": [0.9, 1.0]}
          }
  data:
    - secretKey: PUSHOVER_TOKEN
      remoteRef:
        key: pushover_homelab
        property: password
    - secretKey: PUSHOVER_USER
      remoteRef:
        key: pushover_homelab
        property: username
    - secretKey: LITELLM_AUTH_TOKEN
      remoteRef:
        key: CLAUDE_LITELLM
        property: password
    - secretKey: NEXTCLOUD_USERNAME
      remoteRef:
        key: nextcloud-app
        property: username
    - secretKey: NEXTCLOUD_PASSWORD
      remoteRef:
        key: nextcloud-app
        property: password
