---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: openwebui-secret
    template:
      engineVersion: v2
      data:
        DB_TYPE: postgresdb
        DB_POSTGRESDB_DATABASE: &dbName openwebui
        DB_POSTGRESDB_HOST: &dbHost "dev-postgres16-rw.database.svc.cluster.local"
        DB_POSTGRESDB_USER: &dbUser "{{ .OPENWEBUI__POSTGRES_USER }}"
        DB_POSTGRESDB_PASSWORD: &dbPass "{{ .OPENWEBUI__POSTGRES_PASSWORD }}"
        DB_POSTGRESDB_PORT: "5432"
        DATABASE_URL: "postgresql://{{ .OPENWEBUI__POSTGRES_USER }}:{{ .OPENWEBUI__POSTGRES_PASSWORD }}@dev-postgres16-rw.database.svc.cluster.local:5432/openwebui?sslmode=disable"
        WEBUI_SECRET_KEY: "{{ .OPENWEBUI_WEBUI_SECRET_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: cloudnative-pg
        property: password
    - secretKey: OPENWEBUI__POSTGRES_USER
      remoteRef:
        key: openwebui-db
        property: username
    - secretKey: OPENWEBUI__POSTGRES_PASSWORD
      remoteRef:
        key: openwebui-db
        property: password
    - secretKey: OPENWEBUI_WEBUI_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5446b60e-13c9-4eeb-b23d-b61b4664d71c
        property: OPENWEBUI_WEBUI_SECRET_KEY
