---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: linkwarden-secret
    template:
      engineVersion: v2
      data:
        # NEXTAUTH_URL: "https://linkwarden.${SECRET_DOMAIN}"
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
        # MEILI_MASTER_KEY: "VERY_SENSITIVE_MEILI_MASTER_KEY"
        POSTGRES_HOST: &dbHost dev-postgres16-rw.database.svc.cluster.local
        POSTGRES_USER: &dbUser "{{ .LINKWARDEN__POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .LINKWARDEN__POSTGRES_PASSWORD }}"
        DATABASE_URL: "postgresql://{{ .LINKWARDEN__POSTGRES_USER }}:{{ .LINKWARDEN__POSTGRES_PASSWORD }}@dev-postgres16-rw.database.svc.cluster.local:5432/linkwarden"
        # Postgres Init
        INIT_POSTGRES_DBNAME: linkwarden
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: cloudnative-pg
        property: password
    - secretKey: LINKWARDEN__POSTGRES_USER
      remoteRef:
        key: linkwarden-db
        property: username
    - secretKey: LINKWARDEN__POSTGRES_PASSWORD
      remoteRef:
        key: linkwarden-db
        property: password
    - secretKey: NEXTAUTH_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f3c8971f-89d0-468b-b3c5-f67bb251fe9c
        property: NEXTAUTH_SECRET

