---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calibre-web-automated-nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: calibre-web-automated-nextcloud
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NEXTCLOUD_USERNAME: "{{ .NEXTCLOUD_USERNAME }}"
        NEXTCLOUD_PASSWORD: "{{ .NEXTCLOUD_PASSWORD }}"
        OPENROUTER_API_KEY: "{{ .OPENROUTER_API_KEY }}"
  data:
    - secretKey: NEXTCLOUD_USERNAME
      remoteRef:
        key: nextcloud-app
        property: username
    - secretKey: NEXTCLOUD_PASSWORD
      remoteRef:
        key: nextcloud-app
        property: password
    - secretKey: OPENROUTER_API_KEY
      remoteRef:
        key: OPENROUTER_API_KEY
        property: password
