---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calibre-web-automated-nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: calibre-web-automated-nextcloud
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NEXTCLOUD_USERNAME: "{{ .NEXTCLOUD_USERNAME }}"
        NEXTCLOUD_PASSWORD: "{{ .NEXTCLOUD_PASSWORD }}"
        OPENROUTER_API_KEY: "{{ .LITELLM_AUTH_TOKEN }}"
        PUSHOVER_TOKEN: "{{ .PUSHOVER_TOKEN }}"
        PUSHOVER_USER: "{{ .PUSHOVER_USER }}"
  data:
    - secretKey: NEXTCLOUD_USERNAME
      remoteRef:
        key: nextcloud-app
        property: username
    - secretKey: NEXTCLOUD_PASSWORD
      remoteRef:
        key: nextcloud-app
        property: password
    - secretKey: LITELLM_AUTH_TOKEN
      remoteRef:
        key: LITELLM_AUTH_TOKEN
        property: password
    - secretKey: PUSHOVER_TOKEN
      remoteRef:
        key: pushover_homelab
        property: password
    - secretKey: PUSHOVER_USER
      remoteRef:
        key: pushover_homelab
        property: username
